spring:
  temporal:
    namespace: ${TEMPORAL_NAMESPACE}
    connection:
      target: ${TEMPORAL_ADDRESS}
      mtls:
        key-file: ${TEMPORAL_TLS_CLIENT_KEY_PATH}
        cert-chain-file: ${TEMPORAL_TLS_CLIENT_CERT_PATH}
