spring:
  temporal:
    connection:
      mtls:
        key-file: ${TEMPORAL_NEXUS_TLS_CLIENT_KEY_PATH:${TEMPORAL_TLS_CLIENT_KEY_PATH}}
        cert-chain-file: ${TEMPORAL_NEXUS_TLS_CLIENT_CERT_PATH:${TEMPORAL_TLS_CLIENT_CERT_PATH}}
