[project]
name = "order-management-app-ui"
version = "0.1.0"
description = "Order Management App UI"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.2",
    "cryptography>=46.0.3",
    "flask[async]>=3.1.2",
    "openai>=2.14.0",
    "stripe>=14.1.0",
    "temporalio>=1.21.1",
]
