[project]
name = "order-management-app-ui"
version = "0.1.0"
description = "Order Management App UI"
requires-python = ">=3.11"
dependencies = [
    "flask[async]>=3.1.2",
    "temporalio>=1.21.1",
]
